source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PSPageControl_Example', :exclusive => true do
  pod 'PSPageControl', :path => '../'
end

target 'PSPageControl_Tests', :exclusive => true do
  pod 'PSPageControl', :path => '../'
end
